yzu-nlp:
  database:
    host: localhost
    port: 3306
    username: root
    password: 123456
    schema: Questionnaire
  upload:
    user-upload-path: E:\\questionnaire_uploads_test\\
    # D:\\develop_cocos\\
    # E:\\questionnaire_uploads_test\\